# This is part of PDF Support, please read that section of the readme
# Largely based on: https://github.com/wikimedia/mediawiki-services-chromium-render/blob/master/config.dev.yaml
# TODO: rate limits? Can do in caddy? Has a queue system?

# Number of worker processes to spawn.
num_workers: 0

# Logger info
logging:
  level: info
  streams:
  - type: stdout
    named_levels: true

# Statsd metrics reporter
metrics:
  type: log

# TODO: I don't really know what most of this does
services:
  - name: proton
    module: /opt/proton/app.js
    conf:
      port: 3030
      cors: '*'
      cache_control: 's-maxage=600, max-age=600'
      user_agent: 'Resonite Wiki Proton Renderer'
      mw_req:
        method: get
        uri: http://resonite-wiki/w/index.php
        query:
          title: '{{request.params.title}}'
        headers:
          host: '{{request.params.domain}}'
          x-subdomain: '{{if(request.params.mobile, "M", "")}}'
      pdf_options:
        scale: 1
        displayHeaderFooter: false
        printBackground: true
        landscape: false
        pageRanges: ''
        format: 'a4'
        margin:
          top: '0.5in'
          right: '0.5in'
          bottom: '0.75in'
          left: '0.5in'
      puppeteer_options:
        timeout: 30000
        headless: true
        executablePath: '/usr/bin/chromium'
        args:
          - '--no-sandbox'
          - '--disable-setuid-sandbox'
          - '--font-rendering-hinting=medium'
          - '--enable-font-antialiasing'
          - '--hide-scrollbars'
          - '--disable-gpu'
          - '--no-first-run'
          - '--single-process'
          - '--no-zygote'
      render_concurrency: 1
      render_queue_timeout: 60
      render_execution_timeout: 90
      max_render_queue_size: 3