
# Limit the speed of these paths to 100 KB/s :(
<IfModule mod_ratelimit.c>
    <LocationMatch "^/index\.php">
        <If "%{QUERY_STRING} =~ /title=Special:(RecentChanges|Translate|RecentChangesLinked|WhatLinksHere|CreateAccount|UserLogin)/">
            SetOutputFilter RATE_LIMIT
            SetEnv rate-limit 100
        </If>
    </LocationMatch>

    <Location "/api.php">
        SetOutputFilter RATE_LIMIT
        SetEnv rate-limit 100
    </Location>
</IfModule>