name: 'Build and publish a Docker container image'

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '*.md'
  release:
    types:
      - published

permissions:
  packages: write
  contents: read

jobs:
  docker-build:
    runs-on: ubuntu-latest
    name: 'Build & Publish Docker container image'

    steps:
      - name: 'Checkout current repository'
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: true

      - name: 'Build main Wiki Docker image'
        uses: Yellow-Dog-Man/composite-actions-templates/.github/actions/docker-build-push@b4f799dd8ed863b11a1df3e27d1a243e89509dbe
        with:
          docker-image-name: '${{ github.repository }}'
          docker-token: '${{ github.token }}'

      - name: 'Build Docker utilities'
        uses: Yellow-Dog-Man/composite-actions-templates/.github/actions/docker-build-push@b4f799dd8ed863b11a1df3e27d1a243e89509dbe
        with:
          docker-image-name: '${{ github.repository_owner }}/resonite-wiki-utilities'
          docker-token: '${{ github.token }}'
          dockerfile-path: 'Dockerfile.utilities'
